name: Ol Mate Perform Release

# Portions of this workflow are based on https://github.com/anatawa12/AvatarOptimizer/blob/master/.github/workflows/release.yml

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "True to publish release to git, vpm. if false, this creates release asset only"
        type: boolean
        required: false
      version:
        description: "Version to release"
        type: string
        required: false

env:
  PKG_NAME: nadena.dev.modular-avatar
  RELEASE_TYPE: ${{ github.event.inputs.release_kind }}

concurrency:
  group: publish
  cancel-in-progress: true

permissions:
  contents: write
  checks: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
          path: "package.json"
          prop_path: "version"

      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ env.PKG_NAME }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ env.PKG_NAME }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Zip
        run: |
          zip ".github/${{env.zipFile}}" ./* -r -x .github .git '.git/*' '*~/*' '*.ps1*'

      - name: Move zipfile
        run: |
          mv .github/${{env.zipFile}} ${{env.zipFile}}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: package-zip
          path: ${{ env.zipFile }}

      - name: Make Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228
        if: ${{ github.event.inputs.publish == 'true' }}
        with:
          draft: true
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          files: |
            ${{ env.zipFile }}
            package.json
